name: football_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  cached_network_image: ^3.3.1
  ionicons: ^0.2.2
  flutter_local_notifications: ^17.2.3
  intl: ^0.20.2
  shared_preferences: ^2.0.11   # Ajouter cette ligne pour SharedPreferences
  intl_phone_field: ^3.0.1       # Ajoutez cette ligne pour le champ de téléphone avec l'indicatif pays

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - google_fonts/
    - assets/images/
    - assets/images/atleyico.png
    - assets/images/boxde.png
    - assets/images/frankfurt.png
    - assets/images/cl.png
    - assets/images/Basket.jpg
    - assets/images/teniss.png
    - assets/images/lazio.jpg
    - assets/images/kadja.webp
    - assets/images/toronnto.jpg
    - assets/images/brookyln.jpg
    - assets/images/golden.png
    - assets/images/lakers.png
    - assets/images/chicago.png
    - assets/images/boston.png
    - assets/images/miamih.png
    - assets/images/toronnto.jpg
    - assets/images/dallas.jpg
    - assets/images/kodjo.jpg
    
  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: google_fonts/TitilliumWeb-Regular.ttf
        - asset: google_fonts/TitilliumWeb-SemiBold.ttf
          weight: 700
        - asset: google_fonts/TitilliumWeb-SemiBold.ttf
          weight: 500
